package constant

import (
	"github.com/samber/lo"
	"text/template"
)

const (
	App     = "pat"
	Version = "0.0.1"
)

const (
	ConfigFormat = "toml"
)

var ScriptTemplate = lo.Must(template.New("script").Parse(`{{ .Comment }} Generated by {{ .App }} {{ .Version }}
{{ .Comment }} https://github.com/metafates/{{ .App }}
{{ .Comment }} Do not edit this file manually, let {{ .App }} handle it for you :)

{{ .Script }}
`))
