package constant

import "fmt"

const (
	App     = "pat"
	Version = "0.0.1"
)

const (
	ConfigFormat = "toml"
)

var Disclaimer = func(commentToken string) string {
	return fmt.Sprintf(`%[1]s Generated by %[2]s %[3]s
%[1]s https://github.com/metafates/%[2]s
%[1]s Do not edit this file manually, let %[2]s handle it for you :)
`, commentToken, App, Version)
}
